PROG=	all_tests
SRCS=	$(map_tests)
OBJS=	$(map_tests:%.cpp=.o) $(GTESTOBJS)
CXXFLAGS+= \
	-I $(BASE)/sys \
	-I $(LIBEBPFDIR) \
	-I $(GTESTPATH)/googletest/include \
	-Wno-unused-command-line-argument \
	-O0 \
	$(LDFLAGS)
LDFLAGS+=-coverage
LIBS=	-lpthread -lebpf -L${LIBEBPFDIR}

map_tests = \
	map_create_test.cpp \
	map_lookup_test.cpp \
	map_update_test.cpp \
	map_delete_test.cpp \
	map_get_next_key_test.cpp \
	array_map_delete_test.cpp \
	array_map_get_next_key_test.cpp \
	array_map_lookup_test.cpp \
	array_map_update_test.cpp \
	percpu_array_map_delete_test.cpp \
	percpu_array_map_get_next_key_test.cpp \
	percpu_array_map_lookup_test.cpp \
	percpu_array_map_update_test.cpp

map_tests_not_ready = \
	hashtable_map_delete_test.cpp \
	hashtable_map_get_next_key_test.cpp \
	hashtable_map_lookup_test.cpp \
	hashtable_map_update_test.cpp

all: $(PROG)
$(PROG): $(OBJS) ${LIBEBPF}
	$(CXX) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

check:
	-LD_LIBRARY_PATH=$(LIBEBPFDIR) ./$(PROG)

CLEANFILES=	$(PROG) $(OBJS) *.gcda *.gcno
